### PR TITLE
Switch to Go modules

### PR DESCRIPTION
**Pull request by onionltd**
Go Modules is the preferred way to version packages since Go 1.11.

### CODE REVIEW

**Comment by prusnak** [comment]
Thank you very much! I planned to do this for long time!

Is the file `vendor/modules.txt` really necessary? Shouldn't we just remove the whole `vendor` folder and be done with it?

**Comment by onionltd** [comment]
`vendor` directory may still be needed for older versions of Go (everything below 1.11).

The README states that `trezord-go` requires Go >=1.6, however, I found that the build works only with Go >= 1.7 due to `context` package used in `core/core.go`, which was introduced more recently. More importantly, travis jobs build with Go 1.11+, omitting older versions. So there's definitely some inconsistency.

**Comment by prusnak** [comment]
I don't plan to support anything older than 1.11, so let's nuke the `vendor` dir completely. Can you please also adjust README to say we support only Go 1.11+? Thanks!

**Comment by onionltd** [comment]
I've removed the `vendor` directory and updated the README.

I attempted to upgrade the requirements to their latest versions, unfortunately after the upgrade, the build passes only with Go >=1.12. Should we change the minimum supported version to Go 1.12 or leave it as it is, running with outdated packages?

**Comment by prusnak** [comment]
> Should we change the minimum supported version to Go 1.12

Yes, I am fine with this change.

**Comment by onionltd** [comment]
I pushed the changes but there are two failed jobs. First the gometalinter, it fails due to missing dependency. I noticed the project is obsolete and there's an open PR #153 to replace it.

The other failed job is windows build. It fails due to some weird C error. I noticed the same error appears on build for the latest master.

**Comment by prusnak** [comment]
> First the gometalinter, it fails due to missing dependency.

Please fix this by adding the dependency for now. I'll address the PR #153 later.

> I noticed the same error appears on build for the latest master.

That's not right, I fixed this in master meanwhile.

I am changing the target of this branch to the `next` branch (which has the same HEAD as the current `master` with the fix) where we will brew the next version with Go modules support (I prefer to keep `master` stable).

Will you please rebase this PR on top of the current `next`?

**Comment by onionltd** [comment]
> Please fix this by adding the dependency for now. I'll address the PR #153 later.

The missing/broken dependency is a part of gometalinter. I'm not sure why the changes cause the job to fail, I tried with GO111MODULE set to `auto|on`.The result were two different errors. As far as i'm concerned, the package is fubar.

> Will you please rebase this PR on top of the current next? This should fix the "weird C error".

Done.

**Comment by prusnak** [comment]
I rebased the PR #153 into the `next` branch - let's see how that works in the CI.

**Comment by onionltd** [comment]
> I rebased the PR #153 into the next branch - let's see how that works in the CI.

I extracted the core changes from #153, updated them to fit the latest release of golangci-lint and pushed all of it here: https://github.com/onionltd/trezord-go/tree/golangci-lint

What's the best way forward? IMHO drop the commits introduced by merge of #153 and merge changes from `golangci-lint` instead. The CI is going to fail but this time it will fail on linter errors. I'll fix those next.

**Comment by prusnak** [comment]
I pushed changes from your `golangci-lint` branch into `next2` branch.

**Comment by prusnak** [comment]
I changed the base branch of this PR to `next2` - can you please rebase this PR?

**Comment by onionltd** [comment]
It's done.

**Comment by prusnak** [comment]
Thank you very much! I'll merge this into master after 2.0.30 is released, which will be hopefully soon.

**Comment by prusnak** [comment]
Merged into master (even before 2.0.30 which will come soon), thanks again!

**Pull request merged**
