### PR TITLE
Display type on status page correctly

### PR DESCRIPTION
**Pull request by karel-3d**
Based on BcdDevice

Fixes https://github.com/trezor/trezord-go/issues/97

Depends on https://github.com/trezor/trezord-go/pull/70 (freebsd PR) since it touches the same places (I am using `freebsd` branch from this repo, not the one from the PR)

### CODE REVIEW

**Comment by prusnak** [comment]
Please match just the top byte of the bcd. We might want to change the
lower bcd byte in the future, but we'll keep the top byte unchanged (i.e
0x01 for T1 and 0x02 for T2).

**Comment by prusnak** [comment]
Also, we made Emulator bool orthogonal to Model in trezor-core. So
there is no longer {T1, T2, EMU} set, but rather the matrix {EMU, REAL}
x {T1, T2}. Not sure if it make sense to discriminate this in the
bridge, though.

**Comment by karel-3d** [comment]
OK done, it still needs freebsd first.

**Comment by karel-3d** [comment]
Rebased on top of master, merging

**Pull request merged**
