### PR TITLE
Add WDI WinUSB build + install

### PR DESCRIPTION
**Pull request by karel-3d**
Note - I have not yet tested the NSIS installer.

I *have* tested the build and the WDI tool on one Windows 7 computer. It is working and it is correctly installing the driver.

As I have noted privately, we will need to change VID and PID of webusb Trezor 1 (both BL and FW).

### CODE REVIEW

**Comment by karel-3d** [comment]
I have tested the NSIS installer on 32bit win10 and 64bit win10 and they both work (and install the driver).

I have also tested it on offline windows7 computer, where windows update cannot install the driver automatically (so that simulated all the broken Win7 PCs), and it installed the driver there too

So it seems like actually working.

**Comment by prusnak** [comment]
:tada:

**Comment by karel-3d** [comment]
Heh, the WDI driver also actually compiles in the Travis test environment, since it's in Docker :)

**Comment by prusnak** [comment]
Do we really need to ship 2 binaries? (i.e. isn't it enough to have just 32-bit version?)

**Comment by karel-3d** [comment]
You can try to edit the WDI docker build if you are able to do that, I
wasn't.

When building the WDI library as 32bit, it *explicitly states* it will be
incompatible with 64b windows, during the autoconf stage,  and it bundles a
different WDI driver. There is a different folder in WDK (windows driver
kit) for 32b and 64b drivers and the wdi library takes it from different
place during build.

Maybe if we didn't build it in Docker/mingw, it would be possible to build
just one library, but I don't want to do that. (Zadig itself is built using
appveyor, I can't use that.)

**Comment by prusnak** [comment]
LGTM

**Pull request merged**
