### PR TITLE
Make README more up-to-date

### PR DESCRIPTION
**Pull request by igor-hnizdo**
* update batches to GH actions
* remove pre-modules go stuff
* update makefile info
* add info about certificates

### CODE REVIEW

**Comment by tsusanka** [comment]
Merged via https://github.com/trezor/trezord-go/commit/39d21970aae9f130b42c496f12fe11a6dfe5b7ae, I have added few smaller things. Thanks!

**Comment by tsusanka** [comment]
@igor-hnizdo one last thing, do you think you could update the [Changelog](https://github.com/trezor/trezord-go/commit/106378786e9f79452f47fccf666d26942020906d#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR5) real quick?

**Comment by tsusanka** [comment]
Done in https://github.com/trezor/trezord-go/commit/9aa6576af6fabd557bc298d1a12b73170f467a07 👍

**Comment by igor-hnizdo** [comment]
@tsusanka ha I just wanted to get around to it :) thx, sorry

**Comment by tsusanka** [comment]
No worries, it was a quick one.

**Pull request closed without merging**
