### PR TITLE
Remove trezorv2 from HIDAPI

### LINKED ISSUE #288: On macOS 13.3 bridge shows 1 device as 2 devices
Bridge 2.0.32
macOS 13.3.0/13.3.1

- connect just one device (no matter if model T or model One)

- check status page http://127.0.0.1:21325/status/

image (5)

Expected:
- see just the 1 device connected

Actual:
- there is one more weird device shown

detailed logs:
[log (1).gz](https://github.com/trezor/trezor-suite/files/11211989/log.1.gz)

### PR DESCRIPTION
**Pull request by karelbilek**
Fixes #288

### CODE REVIEW

**Comment by karelbilek** [comment]
Please check if the ancient trezors with HID still work after this. But I don't see why they might not.

**Review by tsusanka — APPROVED** [review]
Looks good to me I guess, but I know this part very little. So do not take it for granted, we really need to test it properly.

**Comment by karelbilek** [comment]
The only part it really touches is listing of devices. So if devices are listed properly - both T1, TT and old HID T1 - on all OSes - then all is fine.

**Comment by karelbilek** [comment]
Sorry, no need to test Linux, hidapi is not used on linux.

**Comment by tsusanka** [comment]
Reminder: we need to bump the version in master, tag it in git etc. after this is released. I can do it.

**Comment by bosomt** [comment]
@karelbilek already testing new version 

i see that old devices with ancient bootloaders 1.3.2 or 1.3.2 are listed in trezorctl or in Bridge status page twice /only in normal mode, in bootloader i see only one device.


image

```
 ~  trezorctl list                                                                                                                                                   
bridge:5 - Device is in use by another process
/opt/homebrew/lib/python3.10/site-packages/trezorlib/client.py:280: UserWarning: Firmware is out of date
  self.check_firmware_version(warn_only=True)
bridge:6 - Failed to read details
```

```
 ~  trezorctl list                                                                                                                                                  
bridge:7 - Trezor 1 bootloader
```

**Comment by tsusanka** [comment]
If 1.3.2 is the only troublesome FW / BL I think we can live with that.

**Comment by bosomt** [comment]
retested with newer fw 1.7.1/1.6.1 and it works as expected on macARM and on Win10 platforms.

**Pull request merged**
