### PR TITLE
Add debuglink

### PR DESCRIPTION
**Pull request by karel-3d**
Adding debug link

### CODE REVIEW

**Comment by karel-3d** [comment]
It builds!!!

Now let's cross-test it with https://github.com/trezor/connect/tree/develop/src/__tests__

**Comment by karel-3d** [comment]
It should be working now, but it is hard to test.

See the readme'

@szymonlesisz or @matejcik pls test, and if it doesn't work please write me some simple testcase. I won't merge until I get some confirmation that it works on both emulator and at least one of the devices

**Comment by karel-3d** [comment]
I have confirmed that it works, by  adding support to trezor-link/trezor.js and testing that, on t1 with debuglink and on emulator (and in both node and browser)

Merging after cleaning up the commit messages

**Comment by matejcik** [comment]
please also bump version so that I can check if the bridge is new enough

**Comment by karel-3d** [comment]
Usually we do it right before build and testing

I guess I can do it now since the next version is feature complete

**Pull request merged**
